swagger: '2.0'
info:
  title: OLS Product API
  description: API for managing products
  version: "1.0"
consumes:
  - "application/json"
produces:
  - "application/json"

definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: Sample Product
      description:
        type: string
        example: This is a sample product
      price:
        type: number
        format: float
        example: 99.99
      creation_date:
        type: string
        format: date-time
        example: '2023-04-05T00:00:00'
