summary: Update a product by its ID
parameters:
  - in: path
    name: id
    type: integer
    required: true
    description: ID of the product
  - in: body
    name: body
    schema:
      $ref: '#/definitions/Product'
responses:
  200:
    description: Product updated
    schema:
      $ref: '#/definitions/Product'
  404:
    description: Product not found
